/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#23005c",
        "secondary": "#4cd7f6",
        "outline": "#958ea0",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-primary": "#6d3bd7",
        "on-primary": "#3c0091",
        "on-secondary-fixed-variant": "#004e5c",
        "on-primary-fixed-variant": "#5516be",
        "on-tertiary": "#002e6a",
        "surface-container-lowest": "#060e20",
        "on-surface-variant": "#cbc3d7",
        "inverse-surface": "#dae2fd",
        "surface-container-high": "#222a3d",
        "surface-variant": "#2d3449",
        "primary-fixed-dim": "#d0bcff",
        "on-surface": "#dae2fd",
        "tertiary-fixed": "#d8e2ff",
        "inverse-on-surface": "#283044",
        "secondary-container": "#03b5d3",
        "on-tertiary-fixed-variant": "#004395",
        "primary-fixed": "#e9ddff",
        "surface-dim": "#0b1326",
        "surface-container": "#171f33",
        "on-secondary-container": "#00424e",
        "tertiary-fixed-dim": "#adc6ff",
        "on-background": "#dae2fd",
        "on-tertiary-fixed": "#001a42",
        "primary-container": "#a078ff",
        "surface-bright": "#31394d",
        "on-primary-container": "#340080",
        "outline-variant": "#494454",
        "tertiary-container": "#4d8eff",
        "on-secondary-fixed": "#001f26",
        "error": "#ffb4ab",
        "background": "#0b1326",
        "surface-tint": "#d0bcff",
        "surface-container-highest": "#2d3449",
        "on-tertiary-container": "#00285d",
        "secondary-fixed": "#acedff",
        "surface-container-low": "#131b2e",
        "surface": "#0b1326",
        "on-error-container": "#ffdad6",
        "primary": "#d0bcff",
        "tertiary": "#adc6ff",
        "error-container": "#93000a",
        "on-secondary": "#003640",
        "on-error": "#690005",
        // Legacy colors to prevent page-level compilation issues
        dark: {
          50: '#f8f8fc',
          100: '#e8e8f0',
          200: '#c5c5d8',
          300: '#9999b8',
          400: '#6b6b8f',
          500: '#4d4d72',
          600: '#3d3d5c',
          700: '#2d2d47',
          800: '#1e1e35',
          900: '#0b1326',
          950: '#060e20',
        }
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "unit": "4px",
        "margin-mobile": "16px",
        "container-max-width": "1440px",
        "margin-desktop": "40px"
      },
      fontFamily: {
        "headline-lg": ["Geist", "Inter", "sans-serif"],
        "body-lg": ["Geist", "Inter", "sans-serif"],
        "display-lg": ["Geist", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Geist", "Inter", "sans-serif"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "body-md": ["Geist", "Inter", "sans-serif"],
        "headline-md": ["Geist", "Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        sans: ["Geist", "Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.04em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "500"}]
      },
      animation: {
        'slide-in': 'slideIn 0.3s ease-out',
        'fade-in': 'fadeIn 0.4s ease-out',
        'scale-in': 'scaleIn 0.2s ease-out',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'shimmer': 'shimmer 1.5s infinite',
        'float': 'float 3s ease-in-out infinite',
        'gradient-move': 'gradientMove 5s ease infinite',
      },
      keyframes: {
        slideIn: {
          '0%': { transform: 'translateX(-10px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200px 0' },
          '100%': { backgroundPosition: 'calc(200px + 100%) 0' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-6px)' },
        },
        gradientMove: {
          '0%': { 'background-position': '0% 50%' },
          '50%': { 'background-position': '100% 50%' },
          '100%': { 'background-position': '0% 50%' },
        }
      },
      boxShadow: {
        'card': '0 4px 24px rgba(0,0,0,0.4)',
        'card-hover': '0 8px 40px rgba(160, 120, 255, 0.25)',
        'glow': '0 0 20px rgba(160, 120, 255, 0.4)',
        'glow-green': '0 0 20px rgba(76, 215, 246, 0.4)',
        'glow-red': '0 0 20px rgba(255, 180, 171, 0.4)',
      },
    },
  },
  plugins: [],
}
